project_id = "ocytwtlgmzeouujaxjwx"

[functions.generate-questions]
verify_jwt = false

[functions.reset-leaderboard]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.adjust-points]
verify_jwt = false

[functions.toggle-admin]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.expire-premium]
verify_jwt = false

[functions.check-premium-status]
verify_jwt = false

[functions.daily-challenge]
verify_jwt = false

[functions.friend-suggestions]
verify_jwt = false