project_id = "ocytwtlgmzeouujaxjwx"

[functions.generate-questions]
verify_jwt = false

[functions.reset-leaderboard]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.adjust-points]
verify_jwt = false

[functions.toggle-admin]
verify_jwt = false
